project_id = "fydejpafounkajnxsknj"

[api]
enabled = true
port = 54321

[functions.rl-pipeline]
verify_jwt = false

[functions.country-analysis]
verify_jwt = false

[functions.fetch-articles]
verify_jwt = false

[auth]
enabled = true
site_url = "http://localhost:3000"
